name: absen_dosen_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  fluttertoast: ^8.2.2
  image_picker: ^0.8.9
  firebase_storage: ^11.2.3
  intl: ^0.18.1
  camera: ^0.10.5+2
  shared_preferences: ^2.1.2
  lottie: ^2.4.0
  http: ^0.13.3
  http_parser: ^4.0.2
  geolocator: ^10.1.0
  flutter_image_compress: ^2.1.0
  
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  dio: ^5.3.3
  permission_handler: ^11.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/



